version: "3.8"

services:

  # ================= MYSQL USER =================
  mysql-user:
    image: mysql:8
    container_name: mysql-user
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Abhinay@123
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql
      - ./database-init/user.sql:/docker-entrypoint-initdb.d/init.sql

  # ================= MYSQL SHOP =================
  mysql-shop:
    image: mysql:8
    container_name: mysql-shop
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Abhinay@123
      MYSQL_DATABASE: shopdb
    ports:
      - "3308:3306"
    volumes:
      - mysql_shop_data:/var/lib/mysql
      - ./database-init/shop.sql:/docker-entrypoint-initdb.d/init.sql

  # ================= MYSQL APPOINTMENT =================
  mysql-appointment:
    image: mysql:8
    container_name: mysql-appointment
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Abhinay@123
      MYSQL_DATABASE: appointmentdb
    ports:
      - "3309:3306"
    volumes:
      - mysql_appointment_data:/var/lib/mysql
      - ./database-init/appointment.sql:/docker-entrypoint-initdb.d/init.sql


  # ================= MYSQL PAYMENT =================
  mysql-payment:
    image: mysql:8
    container_name: mysql-payment
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Abhinay@123
      MYSQL_DATABASE: paymentdb
    ports:
      - "3310:3306"
    volumes:
      - mysql_payment_data:/var/lib/mysql
      - ./database-init/payment.sql:/docker-entrypoint-initdb.d/init.sql


  # ================= REDIS =================
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"


  # ================= RABBITMQ =================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"


  # ================= USER SERVICE =================
  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "5001:5001"
      - "50051:50051"
    depends_on:
      - mysql-user
    volumes:
      - ./shared:/app/shared
    environment:
      PORT: 5001
      DB_HOST: mysql-user
      DB_USER: root
      DB_PASSWORD: Abhinay@123
      DB_NAME: userdb
      JWT_SECRET: supersecretkey


  # ================= SHOP SERVICE =================
  shop-service:
    build: ./shop-service
    container_name: shop-service
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      - mysql-shop
      - redis
      - rabbitmq
    volumes:
      - ./shared:/app/shared
    environment:
      PORT: 5002
      DB_HOST: mysql-shop
      DB_USER: root
      DB_PASSWORD: Abhinay@123
      DB_NAME: shopdb
      REDIS_URL: redis://redis:6379


  # ================= APPOINTMENT SERVICE =================
  appointment-service:
    build: ./appointment-service
    container_name: appointment-service
    restart: always
    ports:
      - "5003:5003"
    depends_on:
      - mysql-appointment
      - rabbitmq
    volumes:
      - ./shared:/app/shared
    environment:
      PORT: 5003
      DB_HOST: mysql-appointment
      DB_USER: root
      DB_PASSWORD: Abhinay@123
      DB_NAME: appointmentdb
      RABBITMQ_URL: amqp://rabbitmq


  # ================= PAYMENT SERVICE =================
  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: always
    depends_on:
      - mysql-payment
      - rabbitmq
    environment:
      DB_HOST: mysql-payment
      DB_USER: root
      DB_PASSWORD: Abhinay@123
      DB_NAME: paymentdb
      RABBITMQ_URL: amqp://rabbitmq


  # ================= NOTIFICATION SERVICE =================
  notification-service:
    build: ./notification-service
    env_file:
    - ./notification-service/.env
    container_name: notification-service
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq


  # ================= API GATEWAY =================
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:5000"
    depends_on:
      - user-service
      - shop-service
      - appointment-service
    environment:
      PORT: 5000
      JWT_SECRET: alsjdfklajsdfljadflkasjdfkasbdf,nszbdjnasbdf,jakhsbfkhasbdfas
      USER_SERVICE_URL: http://user-service:5001
      SHOP_SERVICE_URL: http://shop-service:5002
      APPOINTMENT_SERVICE_URL: http://appointment-service:5003
      PAYMENT_SERVICE_URL: http://payment-service:5004


volumes:
  mysql_user_data:
  mysql_shop_data:
  mysql_appointment_data:
  mysql_payment_data: