// redux/appointments/appointmentTypes.js

export const ACTION = {
    // CREATE
    CREATE_APPOINTMENT_REQUEST: "CREATE_APPOINTMENT_REQUEST",
    CREATE_APPOINTMENT_SUCCESS: "CREATE_APPOINTMENT_SUCCESS",
    CREATE_APPOINTMENT_FAILURE: "CREATE_APPOINTMENT_FAILURE",
  
    // USER APPOINTMENTS
    GET_USER_APPOINTMENTS_REQUEST: "GET_USER_APPOINTMENTS_REQUEST",
    GET_USER_APPOINTMENTS_SUCCESS: "GET_USER_APPOINTMENTS_SUCCESS",
    GET_USER_APPOINTMENTS_FAILURE: "GET_USER_APPOINTMENTS_FAILURE",
  
    // BARBER APPOINTMENTS
    GET_BARBER_APPOINTMENTS_REQUEST: "GET_BARBER_APPOINTMENTS_REQUEST",
    GET_BARBER_APPOINTMENTS_SUCCESS: "GET_BARBER_APPOINTMENTS_SUCCESS",
    GET_BARBER_APPOINTMENTS_FAILURE: "GET_BARBER_APPOINTMENTS_FAILURE",
  
    // CANCEL
    CANCEL_APPOINTMENT_REQUEST: "CANCEL_APPOINTMENT_REQUEST",
    CANCEL_APPOINTMENT_SUCCESS: "CANCEL_APPOINTMENT_SUCCESS",
    CANCEL_APPOINTMENT_FAILURE: "CANCEL_APPOINTMENT_FAILURE",
  };