// BookingActionTypes.js
export const ACTION={
    BOOK_APPOINTMENT_REQUEST : 'BOOK_APPOINTMENT_REQUEST',
    BOOK_APPOINTMENT_SUCCESS : 'BOOK_APPOINTMENT_SUCCESS',
    BOOK_APPOINTMENT_FAILURE : 'BOOK_APPOINTMENT_FAILURE',
    FETCH_APPOINTMENTS_REQUEST : 'FETCH_APPOINTMENTS_REQUEST',
    FETCH_APPOINTMENTS_SUCCESS : 'FETCH_APPOINTMENTS_SUCCESS',
    FETCH_APPOINTMENTS_FAILURE : 'FETCH_APPOINTMENTS_FAILURE'
}