// redux/services/serviceTypes.js

export const ACTION = {
    // Create
    CREATE_SERVICE_REQUEST: "CREATE_SERVICE_REQUEST",
    CREATE_SERVICE_SUCCESS: "CREATE_SERVICE_SUCCESS",
    CREATE_SERVICE_FAILURE: "CREATE_SERVICE_FAILURE",
  
    // List by Barber
    GET_SERVICES_BY_BARBER_REQUEST: "GET_SERVICES_BY_BARBER_REQUEST",
    GET_SERVICES_BY_BARBER_SUCCESS: "GET_SERVICES_BY_BARBER_SUCCESS",
    GET_SERVICES_BY_BARBER_FAILURE: "GET_SERVICES_BY_BARBER_FAILURE",
  
    // Update
    UPDATE_SERVICE_REQUEST: "UPDATE_SERVICE_REQUEST",
    UPDATE_SERVICE_SUCCESS: "UPDATE_SERVICE_SUCCESS",
    UPDATE_SERVICE_FAILURE: "UPDATE_SERVICE_FAILURE",
  
    // Delete
    DELETE_SERVICE_REQUEST: "DELETE_SERVICE_REQUEST",
    DELETE_SERVICE_SUCCESS: "DELETE_SERVICE_SUCCESS",
    DELETE_SERVICE_FAILURE: "DELETE_SERVICE_FAILURE",
  };