// redux/shops/shopTypes.js

export const ACTION = {
    GET_SHOPS_REQUEST : "GET_SHOPS_REQUEST",
    GET_SHOPS_SUCCESS : "GET_SHOPS_SUCCESS",
    GET_SHOPS_FAILURE : "GET_SHOPS_FAILURE",

    GET_SHOP_BY_ID_REQUEST : "GET_SHOP_BY_ID_REQUEST",
    GET_SHOP_BY_ID_SUCCESS : "GET_SHOP_BY_ID_SUCCESS",
    GET_SHOP_BY_ID_FAILURE : "GET_SHOP_BY_ID_FAILURE",

    CREATE_SHOP_REQUEST : "CREATE_SHOP_REQUEST",
    CREATE_SHOP_SUCCESS : "CREATE_SHOP_SUCCESS",
    CREATE_SHOP_FAILURE : "CREATE_SHOP_FAILURE"
}
