name: Microservices CI/CD Pipeline

on:
  push:
    branches:
      - main
      - microservices

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install API Gateway dependencies
        run: npm install
        working-directory: Backend-MicroServices/api-gateway

      - name: Install User Service dependencies
        run: npm install
        working-directory: Backend-MicroServices/user-service

      - name: Install Shop Service dependencies
        run: npm install
        working-directory: Backend-MicroServices/shop-service

      - name: Install Appointment Service dependencies
        run: npm install
        working-directory: Backend-MicroServices/appointment-service

      - name: Install Payment Service dependencies
        run: npm install
        working-directory: Backend-MicroServices/payment-service

      - name: Install Notification Service dependencies
        run: npm install
        working-directory: Backend-MicroServices/notification-service

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Images
      - name: Build Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest ./Backend-MicroServices/api-gateway
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest ./Backend-MicroServices/user-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shop-service:latest ./Backend-MicroServices/shop-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/appointment-service:latest ./Backend-MicroServices/appointment-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/payment-service:latest ./Backend-MicroServices/payment-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/notification-service:latest ./Backend-MicroServices/notification-service

      # Push Images to Docker Hub
      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/shop-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/appointment-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/notification-service:latest